### ISSUE TITLE
IMP-ALL DELIVERABLES

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/curatio#3]
[DCUBE REPORT - 1.zip](https://github.com/astpl1998/curatio/files/2795868/DCUBE.REPORT.-.1.zip)
[DCUBE REPORT - 2.zip](https://github.com/astpl1998/curatio/files/2795869/DCUBE.REPORT.-.2.zip)
[DW REPORT.zip](https://github.com/astpl1998/curatio/files/2795870/DW.REPORT.zip)

[CURATIO _SDD_EMOD.pdf](https://github.com/astpl1998/curatio/files/2795850/CURATIO._SDD_EMOD.pdf)
[CURATIO_SDD_INVENTORY.pdf](https://github.com/astpl1998/curatio/files/2795851/CURATIO_SDD_INVENTORY.pdf)
[CURATIO_SDD_PURCHASE.pdf](https://github.com/astpl1998/curatio/files/2795852/CURATIO_SDD_PURCHASE.pdf)
[CURATIO_SDD_SALES & SHIPPING.pdf](https://github.com/astpl1998/curatio/files/2795853/CURATIO_SDD_SALES.SHIPPING.pdf)
![curatio_sdd_sign-off](https://user-images.githubusercontent.com/46194039/51743605-2ef48880-20c3-11e9-85a3-aff8cd336374.jpg)

**Comment by srinivasanbaskaran** [comment]
Attached SDD & PFS.

**Comment by astpl1998** [comment]
As discussed please reupload the deliverables with correctness

**Comment by srinivasanbaskaran** [comment]
All (Latest)PFS & Deliverables attached... 

[PDF_SDD.zip](https://github.com/astpl1998/curatio/files/2874194/PDF_SDD.zip)

[STN - EXPORT ITEM.zip](https://github.com/astpl1998/curatio/files/2874162/STN.-.EXPORT.ITEM.zip)
[DCUBE REPORTS.zip](https://github.com/astpl1998/curatio/files/2874165/DCUBE.REPORTS.zip)
[DW REPORTS.zip](https://github.com/astpl1998/curatio/files/2874166/DW.REPORTS.zip)
[EDK.zip](https://github.com/astpl1998/curatio/files/2874167/EDK.zip)

**Comment by srinivasanbaskaran** [comment]
Mam,
Please Check & Confirm the deliverables. From myside, Its verified. Please do the needful from yourside
